# Customer Churn Prediction using ANN

## Importing & Cleaning Dataset 

In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv("Churn_Modelling.csv")

In [3]:
df.head(5)

RowNumber  CustomerId   Surname  CreditScore Geography  Gender  Age  \
0          1    15634602  Hargrave          619    France  Female   42   
1          2    15647311      Hill          608     Spain  Female   41   
2          3    15619304      Onio          502    France  Female   42   
3          4    15701354      Boni          699    France  Female   39   
4          5    15737888  Mitchell          850     Spain  Female   43   

   Tenure    Balance  NumOfProducts  HasCrCard  IsActiveMember  \
0       2       0.00              1          1               1   
1       1   83807.86              1          0               1   
2       8  159660.80              3          1               0   
3       1       0.00              2          0               0   
4       2  125510.82              1          1               1   

   EstimatedSalary  Exited  
0        101348.88       1  
1        112542.58       0  
2        113931.57       1  
3         93826.63       0  
4         79084.10       0

In [4]:
df.shape

(10000, 14)

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 14 columns):
 #   Column           Non-Null Count  Dtype  
---  ------           --------------  -----  
 0   RowNumber        10000 non-null  int64  
 1   CustomerId       10000 non-null  int64  
 2   Surname          10000 non-null  object 
 3   CreditScore      10000 non-null  int64  
 4   Geography        10000 non-null  object 
 5   Gender           10000 non-null  object 
 6   Age              10000 non-null  int64  
 7   Tenure           10000 non-null  int64  
 8   Balance          10000 non-null  float64
 9   NumOfProducts    10000 non-null  int64  
 10  HasCrCard        10000 non-null  int64  
 11  IsActiveMember   10000 non-null  int64  
 12  EstimatedSalary  10000 non-null  float64
 13  Exited           10000 non-null  int64  
dtypes: float64(2), int64(9), object(3)
memory usage: 1.1+ MB


In [6]:
df.describe()

RowNumber    CustomerId   CreditScore           Age        Tenure  \
count  10000.00000  1.000000e+04  10000.000000  10000.000000  10000.000000   
mean    5000.50000  1.569094e+07    650.528800     38.921800      5.012800   
std     2886.89568  7.193619e+04     96.653299     10.487806      2.892174   
min        1.00000  1.556570e+07    350.000000     18.000000      0.000000   
25%     2500.75000  1.562853e+07    584.000000     32.000000      3.000000   
50%     5000.50000  1.569074e+07    652.000000     37.000000      5.000000   
75%     7500.25000  1.575323e+07    718.000000     44.000000      7.000000   
max    10000.00000  1.581569e+07    850.000000     92.000000     10.000000   

             Balance  NumOfProducts    HasCrCard  IsActiveMember  \
count   10000.000000   10000.000000  10000.00000    10000.000000   
mean    76485.889288       1.530200      0.70550        0.515100   
std     62397.405202       0.581654      0.45584        0.499797   
min         0.000000       1.000000      0.00000        0.000000   
25%         0.000000       1.000000      0.00000        0.000000   
50%     97198.540000       1.000000      1.00000        1.000000   
75%    127644.240000       2.000000      1.00000        1.000000   
max    250898.090000       4.000000      1.00000        1.000000   

       EstimatedSalary        Exited  
count     10000.000000  10000.000000  
mean     100090.239881      0.203700  
std       57510.492818      0.402769  
min          11.580000      0.000000  
25%       51002.110000      0.000000  
50%      100193.915000      0.000000  
75%      149388.247500      0.000000  
max      199992.480000      1.000000

In [7]:
print(df.isnull().values.any()) 

False


In [8]:
#dropping unwanted columns

df.drop(columns = ['RowNumber','CustomerId','Surname'],inplace=True)

In [9]:
# converting categorical data into numerical data

df = pd.get_dummies(df,columns=['Geography','Gender'],drop_first=True)

## Train test and split

In [10]:
X = df.drop(columns=['Exited'])
y = df['Exited'].values

from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2,random_state=0)

In [11]:
X

CreditScore  Age  Tenure    Balance  NumOfProducts  HasCrCard  \
0             619   42       2       0.00              1          1   
1             608   41       1   83807.86              1          0   
2             502   42       8  159660.80              3          1   
3             699   39       1       0.00              2          0   
4             850   43       2  125510.82              1          1   
...           ...  ...     ...        ...            ...        ...   
9995          771   39       5       0.00              2          1   
9996          516   35      10   57369.61              1          1   
9997          709   36       7       0.00              1          0   
9998          772   42       3   75075.31              2          1   
9999          792   28       4  130142.79              1          1   

      IsActiveMember  EstimatedSalary  Geography_Germany  Geography_Spain  \
0                  1        101348.88              False            False   
1                  1        112542.58              False             True   
2                  0        113931.57              False            False   
3                  0         93826.63              False            False   
4                  1         79084.10              False             True   
...              ...              ...                ...              ...   
9995               0         96270.64              False            False   
9996               1        101699.77              False            False   
9997               1         42085.58              False            False   
9998               0         92888.52               True            False   
9999               0         38190.78              False            False   

      Gender_Male  
0           False  
1           False  
2           False  
3           False  
4           False  
...           ...  
9995         True  
9996         True  
9997        False  
9998         True  
9999        False  

[10000 rows x 11 columns]

In [12]:
y

array([1, 0, 1, ..., 1, 1, 0], dtype=int64)

## Scaling the data

In [13]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()

X_train_trf = scaler.fit_transform(X_train)
X_test_trf = scaler.transform(X_test)

In [14]:
X_train_trf

array([[ 0.16958176, -0.46460796,  0.00666099, ..., -0.5698444 ,
         1.74309049, -1.09168714],
       [-2.30455945,  0.30102557, -1.37744033, ...,  1.75486502,
        -0.57369368,  0.91601335],
       [-1.19119591, -0.94312892, -1.031415  , ..., -0.5698444 ,
        -0.57369368, -1.09168714],
       ...,
       [ 0.9015152 , -0.36890377,  0.00666099, ..., -0.5698444 ,
        -0.57369368,  0.91601335],
       [-0.62420521, -0.08179119,  1.39076231, ..., -0.5698444 ,
         1.74309049, -1.09168714],
       [-0.28401079,  0.87525072, -1.37744033, ...,  1.75486502,
        -0.57369368, -1.09168714]])

In [15]:
X_test_trf

array([[-0.55204276, -0.36890377,  1.04473698, ...,  1.75486502,
        -0.57369368, -1.09168714],
       [-1.31490297,  0.10961719, -1.031415  , ..., -0.5698444 ,
        -0.57369368, -1.09168714],
       [ 0.57162971,  0.30102557,  1.04473698, ..., -0.5698444 ,
         1.74309049, -1.09168714],
       ...,
       [-0.74791227, -0.27319958, -1.37744033, ..., -0.5698444 ,
         1.74309049,  0.91601335],
       [-0.00566991, -0.46460796, -0.33936434, ...,  1.75486502,
        -0.57369368,  0.91601335],
       [-0.79945688, -0.84742473,  1.04473698, ...,  1.75486502,
        -0.57369368,  0.91601335]])

## Training and Evaluating 

In [16]:
import tensorflow
from tensorflow import keras
from tensorflow.keras import Sequential 
from tensorflow.keras.layers import Dense

In [17]:
model = Sequential()

In [18]:
model.add(Dense(10,activation="sigmoid",input_dim=11))
model.add(Dense(5,activation="sigmoid"))
model.add(Dense(1,activation="sigmoid"))

C:\Users\Shiva\anaconda3\Lib\site-packages\keras\src\layers\core\dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


In [19]:
model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━┓
┃ Layer (type)                         ┃ Output Shape                ┃         Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━┩
│ dense (Dense)                        │ (None, 10)                  │             120 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_1 (Dense)                      │ (None, 5)                   │              55 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_2 (Dense)                      │ (None, 1)                   │               6 │
└──────────────────────────────────────┴─────────────────────────────┴─────────────────┘

 Total params: 181 (724.00 B)

 Trainable params: 181 (724.00 B)

 Non-trainable params: 0 (0.00 B)

In [20]:
model.compile(loss='binary_crossentropy',optimizer='Adam')

In [21]:
model.fit(X_train_trf,y_train,epochs=100)

Epoch 1/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 776us/step - loss: 0.7672
Epoch 2/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 728us/step - loss: 0.5282
Epoch 3/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 721us/step - loss: 0.4892
Epoch 4/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 717us/step - loss: 0.4802
Epoch 5/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 738us/step - loss: 0.4670
Epoch 6/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 735us/step - loss: 0.4656
Epoch 7/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 865us/step - loss: 0.4460
Epoch 8/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 794us/step - loss: 0.4500
Epoch 9/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 746us/step - loss: 0.4391
Epoch 10/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 775us/step - loss: 0.4299
Epoch 11/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 743us/step - loss: 0.4323
Epoch 12/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 726us/step - loss: 0.4278
Epoch 13/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 750us/step - loss: 0.4199
Epoch 14/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 726us/step - loss: 0.4177
Epoch 15/100
25

In [22]:
model.layers[0].get_weights()

[array([[-0.13424441, -0.00851069,  0.26359648, -0.05619122,  0.06163661,
          0.2439517 , -0.1607055 ,  0.04906212,  0.28027952, -0.28789786],
        [ 1.2218548 , -1.3704215 , -2.6346965 , -2.0347843 , -2.17706   ,
          0.2540967 , -0.16955338,  0.21049422, -0.48203716, -1.7682956 ],
        [ 0.1942238 , -0.00842403,  0.32144392, -0.23873928, -0.33429378,
         -0.05017816, -0.14460619,  0.3788898 ,  0.10718077,  0.07873388],
        [ 0.30811313,  0.38956243,  0.92075986, -0.01988229,  0.2654818 ,
          0.32591423,  0.6834337 , -0.7676613 ,  0.8755328 , -0.5903606 ],
        [ 4.195728  , -0.06089116, -0.2097123 , -0.41343233, -0.1516464 ,
          0.47527584,  1.4276385 , -0.33527154,  1.3425936 , -0.25856578],
        [ 0.01785216, -0.3252376 ,  0.14986475,  0.38064593, -0.3101319 ,
          0.23556098, -0.11660877, -0.1541486 ,  0.03494028,  0.18384121],
        [ 0.43655148, -0.59389156, -1.0542325 , -0.03555831, -0.6094492 ,
          2.4986107 , -0.0256489

In [23]:
model.layers[1].get_weights()

[array([[-0.68550915,  2.02865   , -1.1572256 , -1.5573301 ,  1.947981  ],
        [-0.22076166,  0.6735219 , -0.5651732 , -0.03388884,  0.87268835],
        [-0.95338845,  0.98282105, -0.60143393, -1.2049369 ,  1.2959274 ],
        [-0.8568956 , -0.4038437 , -0.49091834, -0.6261196 , -0.27923286],
        [-1.3093079 ,  1.0001936 , -0.5181895 , -0.6060826 ,  0.30806637],
        [-1.3904932 ,  1.1280118 , -0.48175648, -1.053389  ,  0.9797179 ],
        [ 2.368296  , -1.7609302 ,  2.262857  ,  1.4908669 , -2.3006806 ],
        [-0.620894  ,  0.45241427, -0.6426747 , -0.18798603,  0.2420553 ],
        [ 1.7242479 , -1.3590803 ,  1.6027225 ,  2.0365176 , -1.1020999 ],
        [-0.8724589 , -0.5978735 , -0.5580213 , -0.4071856 , -0.28313708]],
       dtype=float32),
 array([ 0.6780663, -1.7095311,  0.7970406,  1.119196 , -1.4490192],
       dtype=float32)]

In [24]:
model.layers[2].get_weights()

[array([[ 2.232853 ],
        [-2.0845647],
        [ 2.5957155],
        [ 2.7045968],
        [-2.5412292]], dtype=float32),
 array([-0.5557283], dtype=float32)]

In [25]:
model.predict(X_test_trf)

63/63 ━━━━━━━━━━━━━━━━━━━━ 0s 959us/step


array([[0.24156268],
       [0.3105851 ],
       [0.17080311],
       ...,
       [0.15142013],
       [0.12235845],
       [0.24723089]], dtype=float32)

In [26]:
y_log = model.predict(X_test_trf)

63/63 ━━━━━━━━━━━━━━━━━━━━ 0s 671us/step


In [27]:
y_pred = np.where(y_log>0.5,1,0)

In [28]:
from sklearn.metrics import accuracy_score
accuracy_score(y_test,y_pred)

0.861